default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: wuff 


development:
  <<: *default
  database: machote_app_dev

test: &test
  <<: *default
  database: machote_app_test

production:
  <<: *default
  database: machote_app_prod

cucumber:
  <<: *test
